package potatobeetlesapp;
import potatobeetlesapp.plants.*;

public class Field extends javax.swing.JPanel {
    private int plantsNumber;
    private int alivePlantsNumber;
    private int infectPlantsNumber;
    private int maxPotatoNumber;
    private int potatoNumber;
    private Plant[] plants;
    
    public Field() {
        initComponents();
        plantsNumber = 130;
        alivePlantsNumber = 0;
        infectPlantsNumber = 0;
        
        plants = new Plant[plantsNumber];
        
        for (int i = 0; i < plantsNumber; i++) {
            plants[i] = new Tuber();
        }
        
        maxPotatoNumber = plantsNumber * 8;
        updateInfo();
    }
    
    public int getMaxPotatoNumber() {
        return maxPotatoNumber;
    }
    
    public int getPotatoNumber() {
        updateInfo();
        return potatoNumber;
    }
    
    public int getPlantsNumber() {
        return plantsNumber;
    }
    
    public int getAlivePlantsNumber() {
        updateInfo();
        return alivePlantsNumber;
    }
    
    private void updateInfo() {
        potatoNumber = 0;
        alivePlantsNumber = 0;
        for (int i = 0; i < plantsNumber; i++) {
            if(plants[i].isAlive()) {
                alivePlantsNumber++;
                potatoNumber += plants[i].getPotatoNumber();
                //proverka na jukov
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(147, 118, 89));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
