package potatobeetlesapp;
import java.awt.Color;
import javax.swing.UIManager;
import potatobeetlesapp.plants.*;

public class Field extends javax.swing.JPanel {
    private int plantsNumber;   //Количество растений
    private int alivePlantsNumber;  //Количество живых растений
    private int infectPlantsNumber; //Количество растений с жуками
    private int maxPotatoNumber;    //Максимальный урожай
    private int potatoNumber;   //Возможный урожай на текущий момент
    private Plant[] plants; //Растения
    
    //Конструктор
    public Field() {
        initComponents();
        plantsNumber = 130;
        plants = new Plant[plantsNumber];
        start();
    }
    
    private void start() {
        alivePlantsNumber = plantsNumber;
        infectPlantsNumber = 0;
        
        for (int i = 0; i < plantsNumber; i++) {
            plants[i] = new Tuber(i);
            //plants[i].setBounds(6 + 56 * (i % 13), 6 + 56 * (i / 13), 50, 50);
            add(plants[i]);
            //plants[i].setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        //setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        }
        remove(plants[5]);
        plants[5] = plants[5].grow();
        add(plants[5]);
        maxPotatoNumber = plantsNumber * 8;
        updateInfo();
    }
    
    //Максимальное количество плодов
    public int getMaxPotatoNumber() {
        return maxPotatoNumber;
    }
    
    //Возможное количество плодов на текущий момент
    public int getPotatoNumber() {
        updateInfo();
        return potatoNumber;
    }
    
    //Количество растений
    public int getPlantsNumber() {
        updateInfo();
        return plantsNumber;
    }
    
    //Количество живых растений
    public int getAlivePlantsNumber() {
        updateInfo();
        return alivePlantsNumber;
    }
    
    //Обновление информации
    private void updateInfo() {
        potatoNumber = 0;
        alivePlantsNumber = 0;
        for (int i = 0; i < plantsNumber; i++) {
            if(plants[i].isAlive()) {
                alivePlantsNumber++;
                potatoNumber += plants[i].getPotatoNumber();
                //proverka na jukov
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(147, 118, 89));
        setFocusable(false);
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
